spring:
  profiles:
    active: dev

#设置使用哪个环境

---
server:
  port: 8090

#因为yml和properties是不一样的
#所以这里的配置文件写法需要修改
#其中，数据前面需要带有空格，免得报错
logging:
  level:
    root: debug
#配置日志级别为debug
#相比来说，yml是重视数据的类型，而不是重视文件格式的类型

name:
  data:
    name1: 123
    name2: 222
    subject:
      - math
      - chinese
      - chemistry

#yml中配置多环境特别简单
#三个横线就表示是一组配置

#spring:
#  profiles: dev
spring:
  config:
    activate:
      on-profile: ${spring.profiles.active}
#上面两种方法都是可以的，只不过目前使用较多的是后面这一种

---

server:
  port: 8090
logging:
  level:
    root: debug
spring:
  config:
    activate:
      on-profile: test


---

server:
  port: 8080
logging:
  level:
    root: debug
spring:
  config:
    activate:
      on-profile: prod
